### ISSUE TITLE
How to use?

### ISSUE THREAD

**Issue by railty** [RaiMan/sikulix2android#1]
Hi, I suppose this is to work with the menu "MenutoolAndroid" in Sikulix2.0.0 IDE? how to use? compile and save under same folder?

Thanks for this great tool

**Comment by RaiMan** [comment]
>  is to work with the menu "MenutoolAndroid" in Sikulix2.0.0 IDE?

No, not the intention. 
2.0.0. still has the bundled Android support known from 1.1.4 snapshots.

The work here is some preparation to have the Android support as an extension (not bundled) in the future (most probably with support for [scrcopy]()). 

... and it is a playground for bringing back the extension feature generally (next candidate: VNC)

So just sit back and watch the next time if interested ;-)

Thanks for kind feedback.
